# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\work\GitLab\T113\qt_prj\ykt_pos_qt\DK_YKT-QT-V3S-master\dispbmp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dispBmp(object):
    def setupUi(self, dispBmp):
        dispBmp.setObjectName("dispBmp")
        dispBmp.resize(400, 300)

        self.retranslateUi(dispBmp)
        QtCore.QMetaObject.connectSlotsByName(dispBmp)

    def retranslateUi(self, dispBmp):
        _translate = QtCore.QCoreApplication.translate
        dispBmp.setWindowTitle(_translate("dispBmp", "Form"))
